#ifndef __MIPSSIMULATOR_PROCESSOR_REGESTERFILE_HPP_
#define __MIPSSIMULATOR_PROCESSOR_REGESTERFILE_HPP_

class RegesterFile
{
public:

private:
};

#endif // __MIPSSIMULATOR_PROCESSOR_REGESTERFILE_HPP_
