#ifndef __MIPSSIMULATOR_PROCESSOR_MIPSPROCESSOR_HPP_
#define __MIPSSIMULATOR_PROCESSOR_MIPSPROCESSOR_HPP_

class MIPSProcessor
{
public:

private:
};

#endif // __MIPSSIMULATOR_PROCESSOR_MIPSPROCESSOR_HPP_
